### ISSUE TITLE
Link Settings Page Up to Model

### ISSUE THREAD

**Issue by joemelt101** [joemelt101/gamer-net#116]

**Comment by HomerGaidarski** [comment]
password change is working, but needs proper error messages and the input filtering we used in register/login

changes pushed to the codeJanitor branch

**Comment by HomerGaidarski** [comment]
All settings stuff linked up to the model and updating correctly. codeJanitor commit 6cbb6fdfc55a1b0be23f5299ceae712a5feb4281
