### ISSUE TITLE
Link Friends.php to model and get functionality working

### ISSUE THREAD

**Issue by joemelt101** [joemelt101/gamer-net#12]
Take a look at the sketches and try and implement this with bootstrap. If you have questions - ask them on Slack. I've created templates to get you started (so we can have a relatively consistent feel) in /gamer-net/documentation/Web Page Templates/.

**Comment by joemelt101** [comment]
Load in user data with getFriends()
See friends
Block friends
Unblock friends
Unfriend someone

**Comment by HomerGaidarski** [comment]
done with modelInterfaceFix merge
