### ISSUE TITLE
Create Add Friend Button on Dashboard Page

### ISSUE THREAD

**Issue by joemelt101** [joemelt101/gamer-net#129]

**Comment by HomerGaidarski** [comment]
this is solved when viewing other people's dashboards, example, I'm logged in as bob and i'm on fred's dashboard page (gamer-net/user/fred). There is a button at the top of the page depending on the relationship between bob and friend.

So for example if bob is already friends with fred, the button will say "unfriend".

There is also a block button, so for example if bob blocks fred, fred can't visit bob's profile page.
