### ISSUE TITLE
Update Landing Page with Our Information

### ISSUE THREAD

**Issue by joemelt101** [joemelt101/gamer-net#43]
**Color Coordinate***

Get rid of portfolio
Adjust about us
Add our pictures and names to meet the team
Delete links
Delete What our Clients Say
Keep Contact Us, but fill with dummy data
Link up bottom GitHub link and delete the rest

*\* Last: Update Links at Top to Reflect Final Page Representation **

**Comment by HomerGaidarski** [comment]
Not really needed
