### ISSUE TITLE
We need to draft all of our SQL statements.

### ISSUE THREAD

**Issue by joemelt101** [joemelt101/gamer-net#6]
Basically, we need to look at our MVP and use that to create a list of SQL statements that will enable a user to do all of those things. Get Ben to validate your statements. Make sure to create your own branch and do a pull request to premaster with this issue attached when you complete your work. The SQL statements should exist each in their own .sql file under the documentation/DML directory. Thanks man :smile: 

**Exact Requirements:**

> Have all insert, update and delete queries required for your application written. They should be 
> 
> separate files in your github REPO under a directory called “DML"

**Comment by HomerGaidarski** [comment]
Wait you want all these statements in separate sql files? Why? I should just put them all in a .txt and then refer to them later when I'm creating the actual model php files.

**Comment by joemelt101** [comment]
Splitting up the queries is not my idea. I'm pretty sure that's what they wanted for Sprint 2. Go ahead and double check the instructions -- but I'm pretty sure that's what I read.

**Comment by HomerGaidarski** [comment]
Completed
